# permissions for end users to edit chubaomonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chubaomonitor-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - chubaomonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - chubaomonitors/status
  verbs:
  - get
