# permissions for end users to view chubaomonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chubaomonitor-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - chubaomonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - chubaomonitors/status
  verbs:
  - get
