apiVersion: cache.example.com/v1alpha1
kind: ChubaoMonitor
metadata:
  namespace: test
  name: chubaomonitor
spec:
  sizeprom: 1
  sizegrafana: 1
  imageprom: prom/prometheus:v2.13.1
  imagegrafana: grafana/grafana:6.4.4
  imagePullPolicyprom: IfNotPresent
  imagePullPolicygrafana: IfNotPresent
  hostPath: 
    path: /var/lib/chubaofs_prometheus
  portprom: 9090
  portgrafana: 3000
